#!/bin/sh

dirs=''
IFS=:
for dir in $XDG_DATA_DIRS; do
	dirs="${dirs}:${dir}/applications"
done; dirs=${dirs:1}


result=''
for dir in $dirs; do
	if stest -dq "$dir" ; then
		result="${result}:$(\ls "$dir" --format=single-column)"
	fi
done; result=${result:1}


stest -fl $dirs | grep -v 'mimeinfo.cache' | sed 's/\.[^./]*$//' | sort -u
