#!/bin/sh

# cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
# cache="$cachedir/dmenu_run_desktop"
# [ ! -e "$cachedir" ] && mkdir -p "$cachedir"

dirs=''
IFS=:
for dir in $XDG_DATA_DIRS; do
	dirs="${dirs}:${dir}/applications"
done; dirs=${dirs:1}


result=''
for dir in $dirs; do
	if stest -dq "$dir" ; then
		result="${result}:$(\ls "$dir" --format=single-column)"
	fi
done; result=${result:1}


stest -fl $dirs | grep -v 'mimeinfo.cache' | sed 's/\.[^./]*$//' | sort -u
